### ISSUE TITLE
Custom refresh interval only refreshes the Shift Selector panel, not the entire dashboard

### ISSUE THREAD

**Issue by G3CK0za** [isaozler/grafana-shift-selector#28] opened 2023-12-07 12:20 UTC
Hi @isaozler,

Thank you for your efforts and the latest version!

There is an issue with the custom refresh interval under the panel options though. The custom refresh interval is only refreshing the Shift Selector panel, not the entire dashboard. So the shift selector will always select the correct shift even if the dashboard is not refreshed. And after auto-selecting the correct shift and changing the absolute time range the dashboard refreshes once due to the change in time range...but that is where it ends. No more dashboard refreshes after that until the shift changes again.

**Comment by isaozler** [comment] 2023-12-10 15:45
Hi @G3CK0za, we had issues when manipulating the general refresh interval. That's why I detached the refresh from the panel refresh. I have looked at the problem you mentioned, and indeed, the refresh parameter is not passed through once the shift is updated. Creating a hotfix for it!

**Comment by isaozler** [comment] 2023-12-10 17:04
The cause of the issue was the TimeSrv service resetting the refresh parameter after the shift was updated, although I was passing the parameter.

<img width="401" alt="image" src="https://github.com/isaozler/grafana-shift-selector/assets/1378630/e83d93db-7c58-4763-9ae2-c808ad572c43">

---

`Grafana Service -> TimeSrv.ts`

<img width="335" alt="image" src="https://github.com/isaozler/grafana-shift-selector/assets/1378630/85a3850e-2a26-4862-8acf-edd9282e145c">

### Solution
The issue is now fixed by resetting the refresh rate if it was set before.

**Comment by isaozler** [comment] 2023-12-10 17:42
Released a new version (0.1.5) and submitted it to Grafana. Closing this issue once the plugin is updated.

**Closed** 2023-12-14 05:20 UTC
Labels: bug
